#!/bin/bash


echo "CREATE USER IF NOT EXISTS 'dbbackup'@'localhost' IDENTIFIED BY  '';
 
GRANT SELECT , 
RELOAD , 
FILE , 
SUPER , 
LOCK TABLES , 
SHOW DATABASES ,
SHOW VIEW ON * . * TO  'dbbackup'@'localhost' IDENTIFIED BY  '' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
FLUSH PRIVILEGES;" | mysql -u root -p6DI+mrlnTW


